server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.210.214:3306/positionback?serverTimezone=Asia/Seoul
    username: gb
    password: 1234

mybatis:
  config-location: classpath:/config/config.xml
  mapper-locations: classpath*:/mapper/*.xml
